from . import device
from . import employee
from . import device_type
from . import device_brand
from . import device_attribute_assignment
from . import device_assignment
from . import device_attribute_value
from . import device_model
from . import device_attribute